repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.74.1
    hooks:
      - id: terraform_checkov
      - id: terraform_docs
      - id: terraform_fmt
      - id: terraform_providers_lock
        args:
          - --args=-platform=darwin_arm64
          - --args=-platform=linux_amd64
      - id: terraform_tflint
      - id: terraform_tfsec
