name: Release and Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false

  deploy:
    name: Deploy to Linode
    runs-on: ubuntu-latest
    env:
      # Needed for remote state
      AWS_ACCESS_KEY_ID: ${{ secrets.LINODE_S3_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.LINODE_S3_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-central-1
      # Provider Config
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.6

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        id: plan
        run: terraform apply -auto-approve